# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-09 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donators',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donator_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('donator_address', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('organ_for_donate', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('find_match', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('patient_address', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('needed_organ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
    ]
