# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_vote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('n_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_dob', models.CharField(max_length=255)),
                ('candidate_email', models.CharField(max_length=255)),
                ('candidate_phone', models.CharField(max_length=255)),
                ('candidate_department', models.CharField(max_length=255)),
                ('candidate_gender', models.CharField(max_length=255)),
                ('candidate_address', models.CharField(max_length=255)),
                ('statement_of_intent', models.CharField(max_length=255)),
                ('candidate_image', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
