# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-11 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block_vote_app', '0002_auto_20240110_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donators',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='P_address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='P_address',
        ),
    ]
