# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-12 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_vote_app', '0003_auto_20240111_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_Time',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_time', models.CharField(max_length=255)),
                ('e_time', models.CharField(max_length=255)),
            ],
        ),
    ]
