# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_vote_app', '0004_vote_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('get_id', models.IntegerField(max_length=255)),
            ],
        ),
    ]
