# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-01-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_vote_app', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote_time',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='get_id',
            field=models.IntegerField(),
        ),
    ]
